TimerLimitInput hook과 util을 분리하였습니다
Bamdoliro/marururu pull request #119
Opened 2023-07-01 15:03 UTC by SEOKKAMONI

## 📄 Summary
> TimerLimitInput hook과 util을 분리하였습니다

<br>

## 🔨 Tasks
- [ ] hook 분리
- [ ] util 분리

<br>

## 🙋🏻 More

하...... 제가 짜도 코드가 잘 안읽히는데.. 다른 사람이 읽힐리가요.. 리팩토링 정말 시급합니다..

2023-07-02 14:43 UTC, SEOKKAMONI commented
코드리뷰 부탁드립니다..

저는 현재 TImeLimitInput 즉 타이머가 있는 인증번호를 입력할때 쓰는 Input을 리팩토링 중입니다

제가 생각하는 현재 코드의 문제점은 개발자가 사용하기 다소 번거롭다입니다

코드를 보시면 

### apps/user/src/app/singup/page.tsx
```tsx
const SignUpPage = () => {
    const {
        handleJoinUserData,
        handleRequestEmailButtonClick,
        handleSignUpButtonClick,
        setCheckTermsAgree,
    } = useSignUp();
    const [timerLimitTime, setTimerLimitTime] = useState(0);
    /**
     * true면 인증 요청을 보낸 상태
     * false면 인증 요청을 아직 보내지 않은 상태
     */
    const requestEmailEnabled = timerLimitTime !== 0;

    return (
        <BaseLayout>
            <StyledSignUpPage>
                <ContentBox>
                    <SignUpBox enabled={requestEmailEnabled}>
                        <Column gap="24px">
                            <ButtonInput
                                label="이메일 인증"
                                buttonText="인증"
                                handleButtonClick={() => {
                                    handleRequestEmailButtonClick();
                                    setTimerLimitTime(300); // 5분
                                }}
                                type="email"
                                placeholder="이메일"
                                width="100%"
                                name="email"
                                onChange={handleJoinUserData}
                                enabled={requestEmailEnabled}
                            />
                            {requestEmailEnabled && (
                                <TimeLimitInput
                                    label="인증코드"
                                    width="100%"
                                    maxLength={6}
                                    msg="발송된 이메일의 인증번호를 입력해주세요."
                                    name="code"
                                    onChange={handleJoinUserData}
                                    timer={timerLimitTime}
                                    setTimer={setTimerLimitTime}
                                />
                            )}
                        </Column>
            </StyledSignUpPage>
        </BaseLayout>
    );
};
```

### 뷰

<img width="496" alt="image" src="https://github.com/Bamdoliro/marururu/assets/102217654/54c226dd-9bd3-462b-9365-90141e3c7535">


코드의 핵심 부분만 가져와보면 다음과 같은 코드인데요 하나씩 설명하자면

우선 TimeLimitInput을 사용하려면 useState를 선언해야합니다 초기값은 0으로 잡습니다 이유는 
```tsx
 const [timerLimitTime, setTimerLimitTime] = useState(0);

 const requestEmailEnabled = timerLimitTime !== 0;
```
enabled 조건문 때문인데요 0일시 파란색 인증 버튼이 활성화되고 0보다 숫자가 크면 인증 버튼이 비활성화되기 때문입니다

```tsx
handleButtonClick={() => {
     handleRequestEmailButtonClick();
     setTimerLimitTime(300); // 5분
 }}
```
그래서 ButtonInput에 버튼을 누를시 setTimerLimitTime(300)으로 timerLimitTime의 값을 갑자기 올리는 이유도 위와 같은 이유에 있습니다

제가 코드가 맘에 들지 않는다고 생각하는 부분은 두가지입니다

```tsx
const [timerLimitTime, setTimerLimitTime] = useState(0);
const requestEmailEnabled = timerLimitTime !== 0;
```

이 두줄을 없앨수는 없을까요?

종현님의 의견을 듣고싶습니다 !
그외 좋은 방법 혹은 레퍼런스가 있다면 공유해주시면 정말 엄청난 도움이 될것같습니다!!!

@manudeli

2023-07-03 13:16 UTC, SEOKKAMONI commented
어찌어찌.. 나름 만족스러운 코드를 얻은것같습니다~! @Bamdoliro/maru-frontend 리뷰 부탁드립니다

2023-07-03 13:40 UTC, arkk200 requested changes

2023-07-03 13:40 UTC, arkk200 commented on packages/maru-ui/components/Input/TimeLimitInput.tsx
> +    setTimerTime,
TimeLimitInput 컴포넌트는 signup 페이지에서밖에 안 쓰이는데 굳이 넘겨 줄 필요가 없는 props가 많아 복잡해보입니다.
필요한 프로퍼티만 써서 프로퍼티 개수를 줄여보는 건 어떤가요?

2023-07-03 13:45 UTC, SEOKKAMONI commented on packages/maru-ui/components/Input/TimeLimitInput.tsx
> +    setTimerTime,
오 좋은 의견인것같습니다 굳이 사용하지 않는 프로퍼티를 선언해주는것은 오히려 복잡하다고 느끼게 할 수 있을것같습니다 좋은 지적 감사합니다 !

2023-07-03 13:52 UTC, arkk200 requested changes

2023-07-03 13:52 UTC, arkk200 commented on packages/maru-ui/components/Input/TimeLimitInput.tsx
>      msg,
label과 msg 프로퍼티도 없애는 건 어떨까요?

2023-07-03 13:57 UTC, SEOKKAMONI commented on packages/maru-ui/components/Input/TimeLimitInput.tsx
>      msg,
엥 없앴는데여..?

2023-07-03 14:49 UTC, arkk200 commented on packages/maru-ui/components/Input/TimeLimitInput.tsx
>      msg,
<img width="778" alt="스크린샷 2023-07-03 오후 11 48 20" src="https://github.com/Bamdoliro/marururu/assets/102217839/9fb30cdb-4466-43f4-bc2d-ec35ecc22049">

최신 커밋에 있는데도 label, msg 프로퍼티가 그대로 있어요

2023-07-03 15:27 UTC, SEOKKAMONI commented on packages/maru-ui/components/Input/TimeLimitInput.tsx
>      msg,
아아 label, msg는 모노레포이고 packages로 전역에 관리되고있기때문에 어드민이나 다른 페이지에서 쓰일수도있으니깐 한정짓지않으려면 남겨두는게 맞는것같습니다

2023-07-03 23:18 UTC, arkk200 commented on packages/maru-ui/components/Input/TimeLimitInput.tsx
>      msg,
알겠습니다

2023-07-03 23:18 UTC, arkk200 approved these changes

2023-07-04 00:00 UTC, merged