원서접수 지원자 정보 퍼블리싱
Bamdoliro/marururu pull request #148
Opened 2023-07-13 04:39 UTC by SEOKKAMONI

## 📄 Summary
> 원서접수 지원자 정보 퍼블리싱을 하였습니다

<br>

## 🔨 Tasks
- [ ] 원서접수 지원자 정보 퍼블리싱

<br>

## 🙋🏻 More
<img width="1470" alt="image" src="https://github.com/Bamdoliro/marururu/assets/102217654/fcb36297-0c8a-4a35-8312-1cf5b6083c17">

2023-07-15 18:56 UTC, qodldks approved these changes
코드에 쓰읍 그 뭐라해야하지 소울이 없어요 소울이...
그 발끝부터 올라오는 그 소울이 더 있었으면 합니다.

2023-07-15 18:57 UTC, SEOKKAMONI commented
> 코드에 쓰읍 그 뭐라해야하지 소울이 없어요 소울이... 그 발끝부터 올라오는 그 소울이 더 있었으면 합니다.

나가주세요

2023-07-15 19:50 UTC, arkk200 requested changes

2023-07-15 19:50 UTC, arkk200 commented on apps/user/src/components/form/지원자정보/ProfileUpload/ProfileUpload.tsx
> +            {profileImage.length !== 0 && (
24번째 줄이랑 똑같이

```suggestion
            {profileImage && (
```
이렇게 바꿔도 될 것 같아요

2023-07-15 19:50 UTC, arkk200 commented on apps/user/src/components/form/지원자정보/ProfileUpload/ProfileUpload.tsx
> +                    isDragging={isDragging}>
제 생각엔 isDragging, onDragEnter 등등 이런 것들을 구조 분해할 필요가 없다고 생각해요.
왜냐하면 이 훅은 이미지 파일을 드래그 앤 드랍할 수 있게 해준다는게 목적인데
Drag and drop에 쓰이는 이런 세부적인 속성을 드러내 관심을 끌 필요가 없다고 생각하기 때문입니다.

```suggestion
    const imageFileDragAndDrop =
        useImageFileDragAndDrop(uploadProfileImageFile);
    const { handleImageFileChange } = useImageFileChange(uploadProfileImageFile);

    return (
        <StyledProfileUpload>
            <Title>증명사진</Title>
            {profileImage ? (
                <ImagePreview src={profileImage} alt="profile-image" />
            ) : (
                <ImageUploadBox
                    {...imageFileDragAndDrop}
                >
```

2023-07-16 05:33 UTC, SEOKKAMONI commented on apps/user/src/components/form/지원자정보/ProfileUpload/ProfileUpload.tsx
> +            {profileImage.length !== 0 && (
오 기본값이 ''이라 true로 처리될줄알았는데 아니였군요 ! 세세하게 봐주셔서 감사합니당~

2023-07-16 05:38 UTC, SEOKKAMONI commented on apps/user/src/components/form/지원자정보/ProfileUpload/ProfileUpload.tsx
> +                    isDragging={isDragging}>
제 생각은 좀 다른데요.. 저런식으로 ... 으로 모든 props를 넘겨주었을때  어디서 정의되고 어떤 프롭스를 포함하는지에 대한 정보가 명확하지않아 별로라고 생각합니다 좀 더 명확하고 어떤 props들을 넘겨주는지 아는게 그 동작에 대해서도 이해가 쉬울것이라고 생각합니다

2023-07-16 05:43 UTC, SEOKKAMONI commented on apps/user/src/components/form/지원자정보/ProfileUpload/ProfileUpload.tsx
> +                    isDragging={isDragging}>
저는 그 컴포넌트에 세부적이거나 부가적인 동작들은 ... 을 쓰는게 좋다고 생각하지만 핵심 동작들은 보여주는게 좋다고 생각합니다 명재님은 어떻게 생각하시나요?

2023-07-16 06:18 UTC, arkk200 commented on apps/user/src/components/form/지원자정보/ProfileUpload/ProfileUpload.tsx
> +                    isDragging={isDragging}>
그렇긴 하네요. 다시 생각해보니 스프레드 프롭스 이점이 프롭스 타입을 명시할 필요없는 자바스크립트에서만 작용할 것 같다고 생각이 드네요.

2023-07-16 06:18 UTC, arkk200 approved these changes

2023-07-16 06:18 UTC, merged