원서접수 전형 선택 페이지 개발
Bamdoliro/marururu pull request #153
Opened 2023-07-16 14:40 UTC by arkk200

## 📄 Summary

> 원서접수 전형 선택 페이지 개발했습니다

<img width="923" alt="스크린샷 2023-07-16 오후 11 37 50" src="https://github.com/Bamdoliro/marururu/assets/102217839/0204b3b6-041f-4b7b-9eea-506eee43fa36">

데이터 형식은 아래와 같아요.

<img width="296" alt="스크린샷 2023-07-16 오후 11 38 19" src="https://github.com/Bamdoliro/marururu/assets/102217839/da206a5c-ccaf-4a0e-8148-bfede9667ab6">

admissions는 입학 전형 선택, specialAdmissions는 특별 전형 선택, equalOpportunityAdmissions는 기회 균등 전형 선택, diversityAdmissions는 사회다양성 전형 선택의 값을 의미합니다.
<br>

## 🔨 Tasks

- [x] 원서접수 전형 선택 페이지 개발하기

<br>

## 🙋🏻 More

2023-07-16 15:59 UTC, SEOKKAMONI reviewed
취어럽베이비취어럽베이비 좀 더 힘을내.. 같이 힘내여
https://www.youtube.com/watch?v=Qoojdi11nC4

힘내라는 의미로 노래 추천하고 갑니다..

2023-07-16 15:59 UTC, SEOKKAMONI commented on apps/user/src/components/form/전형선택/전형선택.tsx
> +        if (e.target.name === 'specialAdmissions') {
```suggestion
    const handleRadioChange: ChangeEventHandler<HTMLInputElement> = (e) => {
    const {name} = e.target;
        if (name === 'specialAdmissions') {
```

고려대학교해주세요

2023-07-16 15:59 UTC, SEOKKAMONI commented on apps/user/src/components/form/전형선택/전형선택.tsx
> +        if (e.target.name === 'specialAdmissions') {
고려해달라는뜻

2023-07-16 15:59 UTC, SEOKKAMONI commented on apps/user/src/components/form/전형선택/전형선택.tsx
> +    console.log(JSON.stringify(selectedAdmissions, null, 2));
```suggestion
```
지워주세요~

2023-07-16 15:59 UTC, SEOKKAMONI commented on apps/user/src/components/form/전형선택/전형선택.tsx
> +    });
주석으로 변수가 각각 어떤것을 의미하는지 알려준다면 유지보수 할 때 편할것같아요  !

2023-07-16 15:59 UTC, SEOKKAMONI commented on apps/user/src/components/form/전형선택/전형선택.tsx
> +                admissions: e.target.value,
이것도 구조분해할당 할수있겠네요!~ 이것도 고려대학교해주세요(고려해달라는뜻)

2023-07-16 15:59 UTC, SEOKKAMONI commented on apps/user/src/components/form/전형선택/전형선택.tsx
> +                [e.target.name]: e.target.value,
이것도 마찬가지입니다~

2023-07-16 15:59 UTC, SEOKKAMONI commented on apps/user/src/components/form/전형선택/전형선택.tsx
> +                onChange={handleRadioChange}
handleRadioChange도 좋지만 정확히 무엇을 핸들링하고있는지 변수에 명시해주면 더 좋은 변수명이 될 것 같습니다 !

2023-07-17 05:04 UTC, SEOKKAMONI requested changes
flex로 언제 바꿔줘요

2023-07-17 05:04 UTC, SEOKKAMONI commented on apps/user/src/components/form/전형선택/전형선택.tsx
> +    };
입하전형 -> 입학전형 오타있습니다

if else 보단 switch case가 더 좋을것같아요 어떻게 생각하세요? 그리고 hooks로 따로 빼서 추상화시켜주면 더 좋은 코드가 될것같습니다 !~

2023-07-17 05:04 UTC, SEOKKAMONI commented on apps/user/src/components/form/전형선택/전형선택.tsx
> +                name="입하전형선택"
```suggestion
                name="입학전형선택"
```

2023-07-17 05:04 UTC, SEOKKAMONI commented on apps/user/src/components/form/전형선택/전형선택.tsx
> +    flex-direction: column;
flex utill 사용해주세요 ~

2023-07-17 05:48 UTC, arkk200 commented on apps/user/src/components/form/전형선택/전형선택.tsx
> +    };
그렇네요 반영하겠습니다

2023-07-19 08:32 UTC, merged