funnel 대체제
Bamdoliro/marururu pull request #154
Opened 2023-07-16 15:33 UTC by SEOKKAMONI

## 📄 Summary
> funnel 대체제를 만들었습니다

<br>

## 🔨 Tasks
- [ ] funnel 대체제 만들기
- [ ] useForm
- [ ] FormController

<br>

## 🙋🏻 More
<img width="792" alt="image" src="https://github.com/Bamdoliro/marururu/assets/102217654/bd08eeea-2bc5-4d31-bd7d-20f2c6e2ae7c">

토스 퍼널 빨리.. app dir 지원해주세여..

2023-07-16 16:12 UTC, arkk200 commented
https://youtu.be/NwLWX2RNVcw?t=578

영상에서처럼 shallow push API를 이용하여 페이지 사이 뒤로가기, 앞으로가기 기능을 추가하는 건 어떤가요?

2023-07-17 03:05 UTC, arkk200 requested changes

2023-07-17 03:05 UTC, arkk200 commented on apps/user/src/app/form/page.tsx
> +    return (
다른 page.tsx 컴포넌트에선 레이아웃을 해당 컴포넌트에서 감쌌는데 FormPage만 따로 레이아웃을 보호자정보, 출신학교및학력 컴포넌트에 감싼 이유가 있을까요?

2023-07-17 03:13 UTC, SEOKKAMONI commented on apps/user/src/app/form/page.tsx
> +    return (
FormController에 위치 떄문입니다 FormLayout으로 감쌀수있지만 그렇게 되다면

컴포넌트 내부에 코드는 괴상해지기 떄문에 컴포넌트에 하나씩 감싸도록해서 저런 코드가 나왔어

2023-07-17 03:17 UTC, SEOKKAMONI commented on apps/user/src/app/form/page.tsx
> +    return (
만약 명재님이 말씀하신대로 코드를 짜면 view 코드가

```tsx
<>
            <Styled보호자정보>
                <Column gap={30}>
                    <Row gap={48} alignItems="center">
                        <Input label="성명" width="100%" />
                        <Input label="전화번호" placeholder="- 없이 입력" width="100%" />
                    </Row>
                    <ButtonInput
                        label="주소"
                        buttonText="검색"
                        handleInputButtonClick={openFindAddressModal}
                        width="100%"
                        value={address}
                        readOnly
                    />
                    <Input label="상세 주소" width="100%" />
                </Column>
            </Styled보호자정보>
            <FormController onPrevious={onPrevious} onNext={onNext} />
            {isOpenFindAddressModal && (
                <FindAddressModal
                    closeModal={() => setIsOpenFindAddressModal(false)}
                    setAddress={setAddress}
                />
            )}
        </>
```

다음과 같이 나오게 되는데 제 생각에는 이것이 오히려 보기 불편하다고 생각하여 독립적으로 감쌋습니다 명재님의 의견이 궁금합니다

2023-07-17 03:26 UTC, arkk200 commented on apps/user/src/app/form/page.tsx
> +    return (
알겠스빈다

2023-07-17 03:26 UTC, arkk200 approved these changes

2023-07-17 03:34 UTC, merged