원서접수 성적입력 페이지 프레임 개발
Bamdoliro/marururu pull request #156
Opened 2023-07-17 09:55 UTC by arkk200

## 📄 Summary

> 원서접수 성적입력 페이지에 프레임을 개발했습니다.

<img width="959" alt="스크린샷 2023-07-17 오후 6 54 24" src="https://github.com/Bamdoliro/marururu/assets/102217839/c3b6c13f-894b-4806-8470-dedf3afcc04c">

<img width="959" alt="스크린샷 2023-07-17 오후 6 54 39" src="https://github.com/Bamdoliro/marururu/assets/102217839/1e0f202e-47f6-46b4-8d07-717cc71e6e5b">

<img width="958" alt="스크린샷 2023-07-17 오후 6 54 49" src="https://github.com/Bamdoliro/marururu/assets/102217839/c69df22d-948b-471b-ac25-4a0b3e0e3918">

<img width="959" alt="스크린샷 2023-07-17 오후 6 55 01" src="https://github.com/Bamdoliro/marururu/assets/102217839/fe18d460-8e96-42ad-98e0-baf99e6c9059">

<br>

## 🔨 Tasks

- [x] 원서접수 성적입력 페이지 개발하기

<br>

## 🙋🏻 More

2023-07-17 11:12 UTC, SEOKKAMONI requested changes

2023-07-17 11:12 UTC, SEOKKAMONI commented on apps/user/src/components/form/성적입력/성적입력.tsx
> +            </Caution>
Custion보단 Desc가 어떨까요? 코드 통일성도 챙기고 의미상에도 Desc가 적절할것같습니다 고려부탁드려요!

2023-07-17 11:12 UTC, SEOKKAMONI commented on apps/user/src/components/form/성적입력/성적입력.tsx
> +                    </Caution>
마찬가지입니다

2023-07-17 11:12 UTC, SEOKKAMONI commented on apps/user/src/components/form/성적입력/성적입력.tsx
> +    margin-bottom: 16px;
```suggestion
    margin: 64px 0px 16px;
```

한줄로 줄일수있을것같네요

2023-07-18 03:08 UTC, arkk200 commented on apps/user/src/components/form/성적입력/성적입력.tsx
> +            </Caution>
그렇긴 하네요. 반영하겠습니다

2023-07-18 03:08 UTC, arkk200 commented on apps/user/src/components/form/성적입력/성적입력.tsx
> +    margin-bottom: 16px;
저게 더 깔끔하긴 하네요

2023-07-18 03:12 UTC, SEOKKAMONI requested changes

2023-07-18 03:12 UTC, SEOKKAMONI commented on apps/user/src/components/form/성적입력/성적입력.tsx
> +                </Button>
이건 map 돌리는게 훨씬 좋을것같아요

2023-07-18 08:05 UTC, arkk200 commented
@SEOKKAMONI 코드리뷰 해주세요............

2023-07-18 10:53 UTC, SEOKKAMONI requested changes

2023-07-18 10:53 UTC, SEOKKAMONI commented on apps/user/src/components/form/성적입력/성적입력.tsx
> +                ))}
우선 지금 컨벤션 상 map에서 돌리는 item들은 네이밍을 item으로 하기로 했으니깐 한번 맞춰주시면 감사하겠습니다..

바꾸는건 추후 이야기해봐요 긍정적으로 생각하고있습니다 !

2023-07-18 10:53 UTC, SEOKKAMONI commented on apps/user/src/components/form/성적입력/성적입력.tsx
> +                    <Desc>*자격증을 중복 소지하고 있을 경우, 최고 수준의 자격증 1개만 인정함</Desc>
통일성있게 Desc css에서 margin bottom 지우고 여기서 style={{}} 넣어주는게 어떤가요.. 고려 부탁

2023-07-19 17:16 UTC, arkk200 commented on apps/user/src/components/form/성적입력/성적입력.tsx
> +                    <Desc>*자격증을 중복 소지하고 있을 경우, 최고 수준의 자격증 1개만 인정함</Desc>
혹시 Desc라는 이름의 역할?이 무엇인지 알 수 있을까요?

2023-07-19 17:16 UTC, arkk200 commented on apps/user/src/components/form/성적입력/성적입력.tsx
> +                ))}
아아 몰랐었습니다

2023-07-19 17:22 UTC, arkk200 commented on apps/user/src/components/form/성적입력/성적입력.tsx
> +                    <Desc>*자격증을 중복 소지하고 있을 경우, 최고 수준의 자격증 1개만 인정함</Desc>
Desc는 폰트 사이즈와 색깔만 선언부에서 정의하고 부가적인 스타일은 style 속성으로 받아야하는 이름인가요?

2023-07-21 03:00 UTC, SEOKKAMONI commented on apps/user/src/components/form/성적입력/성적입력.tsx
> +                    <Desc>*자격증을 중복 소지하고 있을 경우, 최고 수준의 자격증 1개만 인정함</Desc>
우선 Desc는 설명이라는 뜻이고 style 속성으로 받았으면 좋겠다한 이유는
기존에 Desc에 margin-bottom이 있는 상태에서 한 태그는 그냥 ```<desc></desc>``` 사용하고
한 태그는 ```<desc style={{}}></desc>``` style 속성으로 margin-bttom 주면 한번 통일성이 없어지니깐 둘 다 style 속성으로 주면 어떻겠냐라는 뜻이였습니다

2023-07-21 03:46 UTC, SEOKKAMONI approved these changes
깔끔하네여~

2023-07-21 03:46 UTC, SEOKKAMONI commented on apps/user/src/components/form/성적입력/성적입력.tsx
> +const FIELD_DATA = ['성적 입력', '출결상황', '봉사시간', '자격증'];
```suggestion
const FIELD_DATA = ['성적 입력', '출결상황', '봉사시간', '자격증'] as const;
```

2023-07-21 05:12 UTC, merged