원서접수 성적 입력 개발
Bamdoliro/marururu pull request #158
Opened 2023-07-18 14:53 UTC by SEOKKAMONI

## 📄 Summary

> 테이블 Td, Th를 디자인시스템으로 만들어 이제 일반 테이블 태그처럼 사용 할 수 있습니다

<br>

## 🔨 Tasks
- [x] 성적입력 테이블을 디자인 시스템에 넣었습니다
- [x] 성적 데이터 입력 핸들링
- [x] 성적 과목 추가
- [x] 성적 과목 삭제

<br>

## 🙋🏻 More

<img width="1038" alt="image" src="https://github.com/Bamdoliro/marururu/assets/102217654/4f05c67f-791c-456d-a7cb-3c6e831bf27c">

2023-07-18 15:59 UTC, SEOKKAMONI commented
help me........

2023-07-21 05:53 UTC, arkk200 requested changes

2023-07-21 05:53 UTC, arkk200 commented on apps/user/src/components/form/성적입력/GradeCalculator/GradeCalculator.tsx
> +    const newSubjectIdRef = useRef(0);
이 `newSbujectIdRef`를 useAddNewSubject 훅에 넣는게 좀 더 코드가 좋게 보일 것 같은데 어떤가요?

2023-07-21 05:53 UTC, arkk200 commented on apps/user/src/components/form/성적입력/GradeCalculator/GradeCalculatorHeader/GradeCalculatorHeader.tsx
> +            <Row alignItems="center">
이 속성을 빼야할 것 같습니다.

<img width="846" alt="스크린샷 2023-07-21 오후 2 46 35" src="https://github.com/Bamdoliro/marururu/assets/102217839/ef209100-f4f1-4eae-9e73-30be090cb167">

이렇게 되네요?

2023-07-21 06:05 UTC, SEOKKAMONI commented on apps/user/src/components/form/성적입력/GradeCalculator/GradeCalculatorHeader/GradeCalculatorHeader.tsx
> +            <Row alignItems="center">
홀리쓋 ㅇㅋ

2023-07-21 06:05 UTC, SEOKKAMONI commented on apps/user/src/components/form/성적입력/GradeCalculator/GradeCalculator.tsx
> +    const newSubjectIdRef = useRef(0);
훅 안에서는 ref.current만 쓰니깐 ref.current만 넘겨주는게 더 좋다고 생각합니다

2023-07-21 06:06 UTC, SEOKKAMONI commented on apps/user/src/components/form/성적입력/GradeCalculator/GradeCalculator.tsx
> +    const newSubjectIdRef = useRef(0);
미리 걸러서 넘겨준다면 좀 더 명확한 변수명을 지을수있기때문입니다

2023-07-21 06:22 UTC, arkk200 commented on apps/user/src/components/form/성적입력/GradeCalculator/GradeCalculator.tsx
> +    const newSubjectIdRef = useRef(0);
그러니깐
useAddNewSubject를
```tsx
export const useAddNewSubject = (
    setNewSubjectListData: Dispatch<SetStateAction<SubjectDataType[]>>,
) => {
    const newSubjectIdRef = useRef(0);
    const handleAddNewSubjectButtonClick = () => {
        const newSubject = {
            id: newSubjectIdRef.current++,
            subjectName: '',
            grade2_1: 'A',
            grade2_2: 'A',
            grade3_1: 'A',
        };

        setNewSubjectListData((prev) => [...prev, newSubject]);
    };

    return { handleAddNewSubjectButtonClick };
};
```

이런식으로 코드를 안으로 옮기는게 어떤지...?

2023-07-21 06:25 UTC, SEOKKAMONI commented on apps/user/src/components/form/성적입력/GradeCalculator/GradeCalculator.tsx
> +    const newSubjectIdRef = useRef(0);
오옹 님 천재? ㄱㅅㄱㅅ 생각을 왜 못했지

2023-07-21 06:26 UTC, SEOKKAMONI commented on apps/user/src/components/form/성적입력/GradeCalculator/GradeCalculator.tsx
> +    const newSubjectIdRef = useRef(0);
근데 저러면 함수불러올때마다 계속 초기화되지않나요

2023-07-21 06:58 UTC, arkk200 commented on apps/user/src/components/form/성적입력/GradeCalculator/GradeCalculator.tsx
> +    const newSubjectIdRef = useRef(0);
해보니 초기화 되진 않네요

2023-07-21 06:59 UTC, SEOKKAMONI commented on apps/user/src/components/form/성적입력/GradeCalculator/GradeCalculator.tsx
> +    const newSubjectIdRef = useRef(0);
오케이 저 지금 .. 병원이라 집가서 고칠게요

2023-07-21 06:59 UTC, SEOKKAMONI commented on apps/user/src/components/form/성적입력/GradeCalculator/GradeCalculator.tsx
> +    const newSubjectIdRef = useRef(0);
(하튜)

2023-07-21 07:06 UTC, arkk200 requested changes

2023-07-21 07:06 UTC, arkk200 commented on apps/user/src/components/form/성적입력/GradeCalculator/GradeCalculator.tsx
> +                <Button onClick={handleAddNewSubjectButtonClick} icon="ADD_ICON" size="SMALL">
과목 추가를 할 때 자동으로 추가된 행이 보이게 스크롤 내리는 기능을 추가하면 사용자 경험에 좋을 것 같은데 어떻게 생각하시나요?

2023-07-21 07:07 UTC, arkk200 commented on apps/user/src/components/form/성적입력/GradeCalculator/GradeCalculator.tsx
> +                <Button onClick={handleAddNewSubjectButtonClick} icon="ADD_ICON" size="SMALL">
https://velog.io/@wlwl99/React%EB%A1%9C-%EC%B1%84%ED%8C%85%EC%95%B1-%EA%B5%AC%ED%98%84-%EC%8B%9C-%EC%8A%A4%ED%81%AC%EB%A1%A4-%EB%A7%A8-%EC%95%84%EB%9E%98%EB%A1%9C-%EB%82%B4%EB%A6%AC%EB%8A%94-%EB%B2%95

찾아보니 보이려는 요소의 scrollIntoView() 메서드를 호출하면 될 것 같아요

2023-07-21 07:08 UTC, SEOKKAMONI commented on apps/user/src/components/form/성적입력/GradeCalculator/GradeCalculator.tsx
> +                <Button onClick={handleAddNewSubjectButtonClick} icon="ADD_ICON" size="SMALL">
오 좋은것같네요

2023-07-22 01:45 UTC, arkk200 approved these changes

2023-07-22 01:46 UTC, merged