원서접수 페이지에 하위 페이지 내 이동 시 이동 전 페이지의 데이터 보이게 수정하기
Bamdoliro/marururu pull request #188
Opened 2023-08-02 05:24 UTC by arkk200

## 📄 Summary

> 원서접수 페이지에 하위 페이지 내 이동 시 이동 전 페이지의 데이터가 안보이던거 수정했습니다

<br>

## 🔨 Tasks

- [x] 지원자정보 페이지 수정
- [x] 보호자정보 페이지 수정
- [x] 출신학교 및 학력 페이지 수정
- [x] 전형 선택 페이지 수정
- [ ] 자기소개서 페이지 수정

<br>

## 🙋🏻 More

2023-08-02 07:31 UTC, SEOKKAMONI commented
명재 디스코드에서 모각코 할래? 너무 쓸쓸함

2023-08-04 04:02 UTC, SEOKKAMONI requested changes
수고하셨습니다~

2023-08-04 04:02 UTC, SEOKKAMONI commented on apps/user/src/app/form/전형선택/전형선택.hooks.ts
>          setFormType(FormType[value as keyof typeof FormType]);
아아 아래 코드를 보니 이해가 되네요 https://velog.io/@jangws/9.-Else-if%EC%99%80-Else%EB%A5%BC-%ED%94%BC%ED%95%98%EA%B3%A0-Early-Return%ED%95%98%EC%9E%90

early return을 쓰면 더 좋은 코드가 될것같아요!

2023-08-04 04:02 UTC, SEOKKAMONI commented on apps/user/src/components/form/Calculators/GradeCalculator/GradeCalculator.tsx
> +        } else if (newSubjectList.length) footerRef.current?.scrollIntoView();
얼리 리턴 써주세영

2023-08-04 04:02 UTC, SEOKKAMONI commented on packages/maru-ui/src/Radio/Radio.tsx
> +    defaultChecked && console.log(value);
```suggestion
```
console.log 지워주세요

2023-08-04 05:16 UTC, arkk200 commented on apps/user/src/app/form/전형선택/전형선택.hooks.ts
>          setFormType(FormType[value as keyof typeof FormType]);
ㅇㅎ 알겠습니다

2023-08-04 09:19 UTC, SEOKKAMONI approved these changes
수고하셨습니다~

2023-08-04 14:09 UTC, SEOKKAMONI approved these changes
깔끔해졌네여~

2023-08-04 14:10 UTC, merged