프로필 메뉴 제작하기
Bamdoliro/marururu pull request #201
Opened 2023-08-02 19:03 UTC by arkk200

## 📄 Summary

> 프로필 메뉴를 제작해야 합니다.

<br>

## 🔨 Tasks

- [x] 퍼블리싱하기
- [ ] 로그아웃 구현하기

<br>

## 🙋🏻 More

2023-08-04 06:16 UTC, arkk200 commented
@gimhanul 선배... 로그아웃 api가 필요해요...

2023-08-12 02:51 UTC, SEOKKAMONI requested changes

2023-08-12 02:51 UTC, SEOKKAMONI commented on apps/user/src/components/common/Header/Profile/Profile.hooks.ts
> +        Storage.setItem('refresh-token', '');
```suggestion
       localstorage.clear();
```

이렇게 쓸 수 있어요

2023-08-12 02:51 UTC, SEOKKAMONI commented on apps/user/src/components/common/Header/Profile/Profile.hooks.ts
> +        window.location.href = ROUTES.MAIN;
이것들은 mutate 성공시 작동하게 하는게 더 좋을것같아요

2023-08-12 02:51 UTC, SEOKKAMONI commented on apps/user/src/components/common/Header/Profile/Profile.tsx
> +    };
useBoolean 사용하면 불필요하게 state랑 함수를 생성 할 필요가 없어질수있어요!

2023-08-12 02:51 UTC, SEOKKAMONI commented on apps/user/src/services/auth/mutations.ts
> +    return { logoutUserMutate, restMutation };
```suggestion
    return { logoutUserMutate, ...restMutation };
```

2023-08-12 02:51 UTC, SEOKKAMONI commented on apps/user/src/services/auth/api.ts
> +export const deleteUser = async () => {
```suggestion
export const deleteLogoutUser = async () => {
```
는 어떨까요 너무 deleteUser는 계정 삭제 같아요

2023-08-12 03:06 UTC, SEOKKAMONI requested changes

2023-08-12 03:06 UTC, SEOKKAMONI commented on apps/user/src/components/common/Header/Profile/Profile.hooks.ts
> +};
컴포넌트는 나누지 않는게 컨벤션 아니였나요?

2023-08-12 03:06 UTC, SEOKKAMONI commented on apps/user/src/components/common/Header/Profile/Profile.tsx
> +    align-items: flex-end;
flex 유틸 써주세욥

2023-08-12 03:06 UTC, SEOKKAMONI commented on apps/user/src/components/common/Header/Profile/Profile.tsx
> +    align-items: center;
flex 유틸 써주세요

2023-08-12 03:06 UTC, SEOKKAMONI commented on apps/user/src/components/common/Header/Profile/Profile.tsx
> +    align-items: center;
이것도요

2023-08-12 03:30 UTC, arkk200 commented on apps/user/src/components/common/Header/Profile/Profile.hooks.ts
> +};
다른 mutate 함수를 사용한 페이지들을 보니 .hooks.ts 라는 파일을 만들고 있길래 저도 그것에 맞게 로직을 나눠 만들었습니다
그냥 Profile.tsx 파일 안으로 옮기는게 더 깔끔하겠네요

2023-08-12 03:43 UTC, SEOKKAMONI approved these changes
수고하셨어요~~

2023-08-12 03:43 UTC, SEOKKAMONI commented on packages/maru-ui/src/Dropdown/Dropdown.tsx
> +    const handleDropdownItemClick = (data: string) => {
```suggestion
    const handleDropdownItemButtonClick = (data: string) => {
```

2023-08-12 03:43 UTC, SEOKKAMONI commented on apps/user/src/components/common/Header/Profile/Profile.tsx
> +                        <Menu>프로필</Menu>
```suggestion
                        <MenuItem>프로필</MenuItem>
```

컨벤션 list > item 으로 되어있는걸로알고있습니다

2023-08-12 03:44 UTC, merged