인증 전송 제한 로직 구현
Bamdoliro/marururu pull request #247
Opened 2023-08-17 06:45 UTC by SEOKKAMONI

## 📄 Summary

> 인증 전송 제한 로직 구현

<br>

## 🔨 Tasks

- [x] 인증 전송 제한 로직 구현

<br>

## 🙋🏻 More

2023-08-17 06:45 UTC, SEOKKAMONI commented
https://slash.page/ko/libraries/react/react/src/components/DebounceClick/DebounceClick.i18n

이걸 사용하였습니다

2023-08-17 08:46 UTC, arkk200 reviewed
DeboundClick 말고 다른 걸 써야할 것 같아여

2023-08-19 03:36 UTC, SEOKKAMONI commented
> DeboundClick 말고 다른 걸 써야할 것 같아여

그렇네요.. 잘못 적용한것같아요 그냥 만들겠습니다

2023-08-19 04:29 UTC, arkk200 requested changes

2023-08-19 04:29 UTC, arkk200 commented on apps/user/src/app/signup/page.tsx
>                                      handleRequestEmailButtonClick();
```suggestion
                                    if (isButtonDisabled) return;
                                    handleRequestEmailButtonClick();
```
처럼 변경해야할 것 같습니다. 이상하게 ButtonInput 컴포넌트 내에 Button 컴포넌트의 enabled 속성이 false가 되도 클릭되네요.

2023-08-19 04:31 UTC, SEOKKAMONI commented on apps/user/src/app/signup/page.tsx
>                                      handleRequestEmailButtonClick();
한번 확인해보겠습니다~

2023-08-19 04:43 UTC, arkk200 approved these changes
잘 작동하네요~

2023-08-19 04:43 UTC, merged