유저 원서접수 초안 제대로 입력이 제대로 되지 않은 경우 경고가 뜨게 했습니다
Bamdoliro/marururu pull request #263
Opened 2023-08-19 10:09 UTC by arkk200

## 📄 Summary

> 유저 원서접수 초안 제대로 입력하지 않으면 경고가 뜨게 수정했습니다.
Input 컴포넌트에 불린값을 받는 isIncorrect props와 경고 메시지를 받는 msg로 경고를 보이게 하였고, isIncorrect에 불린값을 넣지 않았다면 어떠한 경우에도 경고가 보이지 않게 만들었습니다.
ButtonInput에도 isIncorrect와 msg props를 추가하였고 NumberInput에도 isIncorrect props를 추가하였습니다.
백엔드 코드를 참고하며 개발했습니다.

<br>

## 🔨 Tasks

- [x] 경고 보이게 퍼블리싱 다시하기
- [ ] 제대로 입력된 경우에만 반영하기

<br>

## 🙋🏻 More

2023-08-19 13:08 UTC, SEOKKAMONI requested changes
<img width="775" alt="image" src="https://github.com/Bamdoliro/marururu/assets/102217654/881e21bd-f86b-449c-a38f-5db1084d3481">

시작되었을때부터 에러가 엑티브되는것이 아닌 틀렸을때 엑티브되는것을 말한것같아요 그리고 msg랑 errorMsg랑은 용도가 다릅니다 msg는

<img width="483" alt="image" src="https://github.com/Bamdoliro/marururu/assets/102217654/b599ac6b-4077-42ec-872d-c04ab8d1e540">

아래와 같이 정보를 알려줄때 사용합니다 errorMsg라는 props를 하나 더 만들어야할것같아요

2023-08-19 13:10 UTC, arkk200 commented
ㅇㅎ msg 프롭스가 엇갈리네요 알겠습니다

2023-08-19 13:32 UTC, SEOKKAMONI reviewed
이거 1자를 입력했는데 바로 에러를 띄우면 사용자가 당황할수도있을것같아요 보통의 플로우는

원서초안작성을 했는데 만일 전화번호가 11자가 아니라면

<img width="325" alt="image" src="https://github.com/Bamdoliro/marururu/assets/102217654/01d318a4-79ca-4b57-b0dc-477eb4d08407">


이런식으로 제출 버튼을 누르게되면 에러가 담겨서 옵니다 이러한 데이터를 가지고 핸들링하는것은 어떨까요?

2023-08-19 14:29 UTC, arkk200 commented
근데 그러면 이미 다음으로 넘어간 상태라 에러가 표시가 안돼요

2023-08-19 14:31 UTC, SEOKKAMONI commented
> 근데 그러면 이미 다음으로 넘어간 상태라 에러가 표시가 안돼요

음 일단 알겠습니다 나중에 확인 후 다시 개발해봐요~

2023-08-19 14:35 UTC, SEOKKAMONI requested changes

2023-08-19 14:35 UTC, SEOKKAMONI commented on apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
> +                    isIncorrect={form.education.teacherMobilePhoneNumber.length > 11}
```suggestion
                    isError={form.education.teacherMobilePhoneNumber.length > 11}
```
는 어떨까요?

2023-08-19 14:35 UTC, SEOKKAMONI commented on apps/user/src/hooks/useUser.tsx
> +});
따로 store에 뺴주세요 ~ 다른 store파일 보고 다른 store들과 동일한 방식으로 작성부탁드립니다!

2023-08-19 15:04 UTC, arkk200 commented on apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
> +                    isIncorrect={form.education.teacherMobilePhoneNumber.length > 11}
Error로 하니깐 Input 컴포넌트에서 이게 Error 객체인지 검사한다는 느낌이 들어 Incorrect를 사용했습니다.

2023-08-19 15:10 UTC, arkk200 commented on apps/user/src/hooks/useUser.tsx
> +});
넵

2023-08-19 15:14 UTC, SEOKKAMONI commented on apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
> +                    isIncorrect={form.education.teacherMobilePhoneNumber.length > 11}
음 제생각에는 isError -> true면 에러가 있다 ! 라는 느낌을 주고 개발자에게도 Incorrect보다는 isError가 좀 더 직관적일것같다는 생각이 드는것같아요 명재님이 판단해주세요!

2023-08-19 15:24 UTC, arkk200 commented on apps/user/src/app/form/출신학교및학력/출신학교및학력.tsx
> +                    isIncorrect={form.education.teacherMobilePhoneNumber.length > 11}
isError 쓰는게 프로그래밍에서 많이 익숙한 단어이기도 하니 isError로 고치겠습니다.

2023-08-19 15:34 UTC, SEOKKAMONI requested changes
너무너무 좋습니다 하지만 store는 한 파일에 한개씩이 좋을것같아요 form 폴더에 load.ts를 만들어보는건 어떨까요?

2023-08-19 15:34 UTC, SEOKKAMONI commented on apps/user/src/store/user/user.ts
> +    key: 'save form loaded state',
```suggestion
    key: 'load-save-form',
```
은 어떨까요? 컨벤션을 따른다면 이게 더 좋을것같아요!

2023-08-19 15:34 UTC, arkk200 commented on apps/user/src/store/user/user.ts
> +    key: 'save form loaded state',
아아 알겠습니다

2023-08-19 15:36 UTC, SEOKKAMONI commented on apps/user/src/store/user/user.ts
> +    key: 'save form loaded state',
form 폴더에 만들라구 한 이유는 저장된 원서를 불러오는것이기 때문에 user보단 form이 더 어울린다고 생각하였습니다 또한 form을 load하는것이고 부모에 form폴더라 명시해놨으니 load.ts가 좋을것같아요!

2023-08-20 12:42 UTC, SEOKKAMONI approved these changes
Text로 바꿀수있는것들만 바꿔주세요~ 브랜치파서 ~

2023-08-20 12:42 UTC, SEOKKAMONI commented on apps/user/src/components/form/Calculators/VolunteerCalculator/VolunteerCalculator.tsx
>                          <Hour>시간</Hour>
```suggestion
                        <Text>시간</Text>
```

Text로 쓸 수 있을 것 같아요

2023-08-20 12:46 UTC, arkk200 commented on apps/user/src/components/form/Calculators/VolunteerCalculator/VolunteerCalculator.tsx
>                          <Hour>시간</Hour>
넵 따로 이슈 파서 수정하고 있습니다

2023-08-20 12:46 UTC, merged