어드민 원서관리(메인) 페이지 제작 & 어드민 공지사항 페이지 수정
Bamdoliro/marururu pull request #300
Opened 2023-08-22 03:24 UTC by arkk200

## 📄 Summary

> 어드민 원서관리(메인) 페이지를 제작하고, 어드민 공지사항 페이지와 AppLayout 컴포넌트를 조금 수정했습니다.

<img width="1440" alt="스크린샷 2023-08-22 오후 12 23 50" src="https://github.com/Bamdoliro/marururu/assets/102217839/5cfe9305-c2b6-4063-bf06-b639386d9464">

<br>

## 🔨 Tasks

-

<br>

## 🙋🏻 More

2023-08-22 06:22 UTC, qodldks approved these changes
good

2023-08-22 06:26 UTC, SEOKKAMONI requested changes

2023-08-22 06:26 UTC, SEOKKAMONI commented on apps/admin/src/components/main/FormList/FormList.tsx
> +        | 'FARMING_AND_FISHING';
```suggestion
    type: FormType;
```

아래 정의해놨으니 사용하는것이 좋을것같아요

2023-08-22 06:26 UTC, SEOKKAMONI commented on apps/admin/src/components/main/FormList/FormList.tsx
> +};
type들은 따로 types 폴더에 빼는것은 어떨까요?

2023-08-22 06:53 UTC, arkk200 commented on apps/admin/src/components/main/FormList/FormList.tsx
> +};
넵

2023-08-22 14:31 UTC, SEOKKAMONI requested changes

2023-08-22 14:31 UTC, SEOKKAMONI commented on apps/admin/src/components/main/FormList/FormList.tsx
> +};
```suggestion
const KoreanFormType: Record<FormType, string> = {
    REGULAR: '일반',
    MEISTER_TALENT: '마이스터인재',
    NATIONAL_BASIC_LIVING: '국민기초생활수급자',
    NEAR_POVERTY: '차상위계층',
    NATIONAL_VETERANS: '국가보훈대상자 (국가유공자)',
    ONE_PARENT: '한부모가정',
    FROM_NORTH_KOREA: '북한이탈주민',
    MULTICULTURAL: '다문화가정',
    TEEN_HOUSEHOLDER: '소년소녀가장',
    MULTI_CHILDREN: '다자녀가정자녀',
    FARMING_AND_FISHING: '농어촌지역출신자',
    SPECIAL_ADMISSION: '특례입학대상자전형',
};
```
https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type

Record를 사용해보는건 어떨까요?

2023-08-22 14:31 UTC, SEOKKAMONI commented on apps/admin/src/components/notice/NoticeList/NoticeList.tsx
>  ] as const;
더미 데이터는 mocks폴더로 msw를 사용하면 쿼리를 미리 연결하여 나중에 api가 왔을때 엔드포인트만 바꿔주면되서 더 편해요!

2023-08-22 14:31 UTC, SEOKKAMONI commented on apps/admin/src/components/main/FormList/FormList.tsx
> +}[] = [
type으로 따로 뺴는것이 좋을것같아요

2023-08-24 11:55 UTC, SEOKKAMONI requested changes
수고하셨습니다~

2023-08-24 11:55 UTC, SEOKKAMONI commented on apps/admin/src/app/notice/page.tsx
> +                            style={{ padding: '0 16px 0 10px', justifyContent: 'space-between' }}
```suggestion

```

ADD_ICON을 prop으로 넘기게 되면 padding이 들어가기 떄문에 삭제하셔두 될 것 같습니다~

2023-08-24 11:55 UTC, SEOKKAMONI commented on apps/admin/src/components/main/FormList/FormList.tsx
> +};
constants에 빼는게 좋을 것 같아요!

2023-08-24 11:55 UTC, SEOKKAMONI commented on apps/admin/src/components/main/FormList/FormList.tsx
> +    console.log(formList);
```suggestion
```

2023-08-24 11:55 UTC, SEOKKAMONI commented on apps/admin/src/components/main/FormList/FormList.tsx
> +    const { data: formList } = useFormListQuery();
```suggestion
    const { data: formListData } = useFormListQuery();
```

data 뒤에 붙혀주는것이 컨벤션인걸로 알고있습니다~

2023-08-24 11:55 UTC, SEOKKAMONI commented on apps/admin/src/components/main/FormList/FormList.tsx
> +                ))}
FormList 사용해주세요

2023-08-24 11:55 UTC, SEOKKAMONI commented on apps/admin/src/services/QueryClientProvider.tsx
> +                    },
```suggestion
            new QueryClient({
                defaultOptions: {
                    queries: {
                        refetchOnWindowFocus: false,
                        suspense: true
                    },
```

2023-08-24 11:55 UTC, SEOKKAMONI commented on apps/admin/src/services/QueryClientProvider.tsx
> +interface PropsType {
```suggestion
interface Props {
```

2023-08-25 05:39 UTC, arkk200 commented on apps/admin/src/services/QueryClientProvider.tsx
> +                    },
Suspense를 감싸지 않은 상태에서 suspense: true로 지정하면 에러가 발생하길래 일부러 뺐어요😗

2023-08-25 09:04 UTC, SEOKKAMONI commented on apps/admin/src/services/QueryClientProvider.tsx
> +                    },
음.. 그런데 제 생각에는 suspense를 true로 해놓고 쓰지 않는것에 false를 따로 설정하는게 더 좋을것같아요 왜냐하면 user부분만 봐도 suspense를 쓰는 부분이 안쓰는 부분보다 많기 때문입니다!

2023-08-25 14:03 UTC, arkk200 commented on apps/admin/src/services/QueryClientProvider.tsx
> +                    },
알겠습니다.

2023-08-25 14:04 UTC, arkk200 commented on apps/admin/src/services/QueryClientProvider.tsx
> +                    },
근데 suspense는 기본값이 false 아닌가요?

2023-08-25 14:05 UTC, SEOKKAMONI commented on apps/admin/src/services/QueryClientProvider.tsx
> +                    },
네 맞는습니다 하지만 suspense를 전역에 true로 설정해준다면 suspense가 필요하지않은것에 false로 넣어준다는 말이였습니다

2023-08-26 06:34 UTC, arkk200 commented on apps/admin/src/services/QueryClientProvider.tsx
> +                    },
ㅇㅎ 맞네요~

2023-08-26 14:40 UTC, SEOKKAMONI approved these changes
LGTM

2023-08-26 14:42 UTC, merged