프로그래스바, 자주 묻는 질문, 공지사항, 푸터 최대 회원가입 페이지 CSS 속성 수정하기
Bamdoliro/marururu pull request #349
Opened 2023-08-27 05:43 UTC by arkk200

## 📄 Summary

> 자주 묻는 질문, 공지사항 페이지와 프로그래스바, 푸터에 최대 너비를 추가하였고, 회원가입 페이지에 높이와 관련된 CSS 속성을 수정하였습니다.

<br>

## 🔨 Tasks

-

<br>

## 🙋🏻 More

2023-08-27 12:22 UTC, arkk200 commented
됐노 ㅋ

2023-08-27 12:32 UTC, arkk200 commented
@qodldks 확인 해주세요~

2023-08-27 16:52 UTC, SEOKKAMONI requested changes
max-width: 1240px; 현재 해당 스타일이 중복되는 코드가 상당히 많습니다 AppLayout에 maxWidth 속성을 추가하여 prop으로 넘겨주게 만드는것은 어떨까요?

2023-08-27 17:15 UTC, arkk200 commented
페이지마다 패딩이 각각 다 달라 그렇게 하기엔 어려울 것 같아요~

2023-08-27 23:05 UTC, qodldks reviewed
수많고

2023-08-30 10:54 UTC, SEOKKAMONI approved these changes
LGTM

2023-08-31 06:17 UTC, merged