ADD :: 입학전형 설명회 참가 신청 페이지 퍼블리싱
Bamdoliro/marururu pull request #352
Opened 2023-08-27 15:44 UTC by seola1ne

## 📄 Summary
입학전형 설명회 참가 신청 페이지를 퍼블리싱했습니다. 
>

<br>

## 🔨 Tasks
- 학생/학부모, 교사 내비게이션에 따라 다르게 하기
- 기능 구현하기

<br>

## 🙋🏻 More
![image](https://github.com/Bamdoliro/marururu/assets/89336471/2b7176cd-6a29-4354-8f4c-766dca0be428)

2023-08-27 16:23 UTC, SEOKKAMONI requested changes
당신 그렇게 잘하면서 지금까지 안 한 이유가 뭐야... 짱이잖아..

2023-08-27 16:23 UTC, SEOKKAMONI commented on apps/user/src/app/application/page.tsx
> +                    })}
```suggestion
                    {NAVIGATION_DATA.map(( { route, name }, index) => (
                            <UnderLineButton
                                key={`navigation ${index}`}
                                active={route === pathName}
                                onClick={() => router.push(route)}>
                                {name}
                            </UnderLineButton>
                        );
                   )}
```

이런식으로 한다면 바로 리턴이 됩니당!

2023-08-27 16:23 UTC, SEOKKAMONI commented on apps/user/src/app/application/page.tsx
> +    position: relative;
relative가 따로 필요한 이유가 있나요?

2023-08-27 16:23 UTC, SEOKKAMONI commented on apps/user/src/components/application/status/Status.tsx
> +`;
```suggestion
const StyledStatus = styled.div<{ $applicable: boolean }>`
    height: 32px;
    padding: 0px 10px;
    ${flex({ flexDirection: 'column', justifyContent: 'center', alignItems: 'center' })}
    gap: 10px;
    background-color: ${(props) => (props.$applicable ? 'rgba(37, 124, 255, 0.10)' : 'rgba(244, 67, 54, 0.10)')};
    border: 1px solid ${(props) => (props.$applicable ? color.maruDefault : color.red)};
    border-radius: 100px;
`;
```

boolean을 styled에 prop으로 넘겨줄때는 앞에 $를 붙혀줍니다 또한 구조분해 할당이 아닌 props.~로 넘겨주는게 컨벤션입니다

Ref: https://mygumi.tistory.com/382

2023-08-27 16:23 UTC, SEOKKAMONI commented on apps/user/src/app/application/page.tsx
> +        <AppLayout header footer style={{ padding: '0px 312px', marginTop: 82 }}>
```suggestion
        <AppLayout header footer>
```

저 스타일은 StyledApplicationPage 줘도 동일하게 적용될것같아요 !

2023-08-27 17:00 UTC, arkk200 requested changes
수고핫ㅅㅆ븐디ㅏ!!

2023-08-27 23:04 UTC, qodldks approved these changes
good

2023-08-28 01:06 UTC, seola1ne commented on apps/user/src/app/application/page.tsx
> +    position: relative;
없어도 될 것 같습니다

2023-08-28 10:54 UTC, arkk200 commented
머지 충돌 없애줏-요₩

2023-09-06 03:23 UTC, SEOKKAMONI approved these changes
LGTM

2023-09-07 03:14 UTC, SEOKKAMONI approved these changes

2023-09-07 03:14 UTC, SEOKKAMONI commented on apps/user/src/app/page.tsx
> +    padding: 0 100px 240px;
```suggestion
    padding: 0 100px;
```

2023-09-07 03:45 UTC, arkk200 commented on apps/user/src/app/faq/page.tsx
> +    margin-top: 52px;
margin-top 속성이 안 먹네요..
그리고 제가 마진 탑을 안쓰고 패딩만 사용한 이유는 섹션의 높이 값이 완변하게 100vh - 헤더 높이가 되게 하려고 패딩만 적용한 겁니다......

2023-09-09 14:44 UTC, arkk200 requested changes

2023-09-09 14:44 UTC, arkk200 commented on apps/user/src/components/fair/FairList/FairItem/FairStatus/FairStatus.tsx
> +    padding: 0px 10px;
```suggestion
    padding: 0px 10px;
    white-status: nowrap;
```
처럼 `white-status: nowrap;` 속성을 추가해주세요.

<img width="1033" alt="스크린샷 2023-09-09 오후 11 30 55" src="https://github.com/Bamdoliro/marururu/assets/102217839/7838d12c-1c59-42b3-a9c6-30a52f4f56de">

최소 너비에서 글자가 줄바꿈됩니다.

2023-09-09 14:44 UTC, arkk200 commented on apps/user/src/components/fair/FairList/FairItem/FairItem.tsx
> +    height: 160px;
높이를 추가해야하나요? 디자인의 요구사항이면 모르겠는데 최소 너비에서 밑에 패딩이 침범되네요.

<img width="287" alt="스크린샷 2023-09-09 오후 11 32 37" src="https://github.com/Bamdoliro/marururu/assets/102217839/9a165066-f8c9-4ddd-8bc4-56296658bafc">

@qodldks 높이 있는게 맞나요?

2023-09-09 14:44 UTC, arkk200 commented on apps/user/src/components/fair/FairList/FairItem/Status/Status.tsx
이 컴포넌트 FairStatus랑 같은 컴포넌트 같은데 맞나요?

2023-09-09 14:44 UTC, arkk200 commented on apps/user/src/layouts/AppLayout.tsx
> +    background-color: ${(props) => props.backgroundColor};
이렇게 바꾸신 이유가 있나요?

2023-10-29 22:49 UTC, closed without merging