어드민 로그인 페이지 개발했습니다.
Bamdoliro/marururu pull request #362
Opened 2023-08-29 14:26 UTC by arkk200

## 📄 Summary

> 어드민 로그인 페이지를 개발했습니다

<br>

## 🔨 Tasks

-

<br>

## 🙋🏻 More

https://github.com/Bamdoliro/marururu/assets/102217839/6457ee0c-3757-4fce-9f28-746b9be429ae

2023-08-29 15:09 UTC, SEOKKAMONI requested changes
코드 너무 좋아요 ~ 하지만 현재 user에도 동일한 함수들이 있는것으로 알고있습니다 현재 모노레포를 사용하고있어서 키워드로 검색을 한다면 admin, user 총 두번이 떠서 찾기가 힘들어질수있을것같습니다 

LoginAdmin~ 이런식으로 네이밍을 가지고간다면 더 좋을것같아요 !

2023-08-30 02:43 UTC, qodldks approved these changes
퍼블리싱은 잘 됐네요 수고햇슴미다

2023-09-01 02:27 UTC, arkk200 commented
@SEOKKAMONI 리뷰 해주세요

2023-09-04 06:35 UTC, SEOKKAMONI requested changes

2023-09-04 06:35 UTC, SEOKKAMONI commented on apps/admin/src/app/login/page.tsx
> +`;
Column 태그로 대체 할 수 있을것같아요

2023-09-04 06:35 UTC, SEOKKAMONI commented on apps/admin/src/app/page.tsx
> +    const { data: formList } = useFormListQuery();
```suggestion
    const { data: formListData } = useFormListQuery();
```

2023-09-04 06:35 UTC, SEOKKAMONI commented on apps/admin/src/app/page.tsx
>  const Home = () => {
```suggestion
const MainPage = () => {
```

2023-09-04 06:35 UTC, SEOKKAMONI commented on apps/admin/src/services/auth/api.ts
> +    console.log(phoneNumber);
```suggestion
```

2023-09-04 06:42 UTC, SEOKKAMONI commented
다음부턴 task 써주세용~

2023-09-04 14:23 UTC, arkk200 commented
근데 태스크는 이슈에 있는데 써야하나요...?

2023-09-13 12:49 UTC, SEOKKAMONI approved these changes

2023-09-13 17:28 UTC, merged