원서접수 검정고시 추가
Bamdoliro/marururu pull request #382
Opened 2023-09-14 06:40 UTC by SEOKKAMONI

## 📄 Summary

> 원서접수에 검정고시 접수 기능을 추가하였습니다

<br>

## 🔨 Tasks

- 원서 성적 모의 계산 검정고시 추가
- 원서접수 검정고시 추가
- 검정고시 성적 계산 로직 추가
- 성적 계산 버그 수정
- Switch 컴포넌트 추가

<br>

## 🙋🏻 More

https://github.com/Bamdoliro/marururu/assets/102217654/194f1dbb-cb71-43f5-afca-68756e155b04

2023-09-14 06:49 UTC, SEOKKAMONI commented on apps/user/src/app/form/최종제출/최종제출.hooks.ts
> +    console.log(exportFormData);
```suggestion
```

2023-09-14 07:03 UTC, gimhanul commented on apps/user/src/components/form/Calculators/ScoreCalculator/검정고시Calculator/New검정고시CalculatorItem/New검정고시CalculatorItem.tsx
> +const StyledNew검정고시CalculatorItem = styled.div`
... 개웃기다

2023-09-14 07:03 UTC, gimhanul commented on apps/user/src/components/form/Calculators/ScoreCalculator/검정고시Calculator/검정고시Calculator.tsx
> +            alert('1개만 추가 할 수 있습니다.');
```suggestion
            alert('한 개만 추가 할 수 있습니다.');
```

2023-09-14 07:03 UTC, gimhanul commented on apps/user/src/components/form/Calculators/ScoreCalculator/검정고시Calculator/검정고시Calculator.tsx
> +            alert('1개만 추가 할 수 있습니다.');
아니면 그냥 아예 추가해놓고 추가 버튼 없애

2023-09-14 07:35 UTC, arkk200 requested changes
<img width="903" alt="스크린샷 2023-09-14 오후 4 34 32" src="https://github.com/Bamdoliro/marururu/assets/102217839/8791d5d4-72ae-4cef-845f-f81673aeaa38">

원서 작성 페이지에 프로그래스바가 이상해졌네요

2023-09-14 07:40 UTC, arkk200 commented
https://github.com/Bamdoliro/marururu/assets/102217839/c952221e-8b6b-45b4-ab95-00c137ced631


추가 로 검정 고시가 아닌데도 성적 입력 페이지에 출결상황, 봉사시간, 자격증 링크가 클릭이 안돼요.

2023-09-14 07:50 UTC, SEOKKAMONI commented
> <img alt="스크린샷 2023-09-14 오후 4 34 32" width="903" src="https://user-images.githubusercontent.com/102217839/267894744-8791d5d4-72ae-4cef-845f-f81673aeaa38.png">
> 원서 작성 페이지에 프로그래스바가 이상해졌네요

main에 고쳐져있어서 나중에 머지하면 고쳐질것입니다!

2023-09-14 07:58 UTC, arkk200 commented
https://github.com/Bamdoliro/marururu/assets/102217839/a42b0739-c5ac-4512-a35f-da17cb14c285


값 유지도 안돼요

2023-09-14 08:47 UTC, qodldks requested changes
삭제 버튼 셀 옆구리 튀어나온거 해결해주시고
![image](https://github.com/Bamdoliro/marururu/assets/102123549/64ad6253-cece-4a6f-a76c-3d641bf9028d)

alert 메세지도
"선택과목은 하나만 추가할 수 있습니다."로 수정해주세요

2023-09-15 02:08 UTC, arkk200 reviewed
성적 모의 계산에서 졸업 예정/고입검정 값도 원서 접수 페이지에 반영되는건 의도하신건가요?

https://github.com/Bamdoliro/marururu/assets/102217839/1cade330-0d4d-416e-9104-967edf7b9ed9

2023-09-18 15:10 UTC, arkk200 approved these changes
잘 작동하네요~

2023-09-18 15:11 UTC, merged