유저 부분 에러 핸들링 안되는 버그 수정
Bamdoliro/marururu pull request #417
Opened 2023-09-19 08:00 UTC by SEOKKAMONI

## 📄 Summary

> 유저 부분 에러 핸들링 안되는 버그를 수정하였습니다

<br>

## 🔨 Tasks

- 유저 부분 에러 핸들링 안되는 버그 수정

<br>

## 🙋🏻 More

2023-09-19 12:43 UTC, arkk200 approved these changes
error 객체의 response가 있어야만 메시지가 작동되도록 만드셨네요👍

2023-09-19 12:43 UTC, arkk200 commented on apps/user/src/hooks/useApiError.ts
> +        console.log(error);
이 콘솔 로그는 일부러 넣어놓으신건가요?

2023-09-19 12:46 UTC, SEOKKAMONI commented on apps/user/src/hooks/useApiError.ts
> +        console.log(error);
힝 아니요..

2023-09-19 22:33 UTC, SEOKKAMONI commented on apps/user/src/hooks/useApiError.ts
> +        console.log(error);
```suggestion
```

2023-09-20 03:21 UTC, arkk200 reviewed
영상 찍어서 보여주세요~

2023-09-20 03:27 UTC, arkk200 requested changes
사용자가 없다는 에러 메시지는 전에도 말했듯이 보안에 위험이 있을 수 있어요.
똑같이 로그인할 수 없다는 메시지를 보여줘야 할 것 같아요

2023-09-20 04:38 UTC, arkk200 approved these changes
잘 고쳤네요👍

2023-09-20 04:40 UTC, merged