refactor(user): rename DdayBox component, separate components
Bamdoliro/marururu pull request #464
Opened 2023-11-02 11:31 UTC by arkk200

## 📄 Summary

>

<br>

## 🔨 Tasks

-

<br>

## 🙋🏻 More

2023-11-02 14:30 UTC, SEOKKAMONI commented on apps/user/src/components/main/CurrentScheduleBox/CurrentScheduleBox.hooks.ts
> +  };
한 함수가 두개의 역할을 하고 있어서 네이밍이 명시적이지 않게 나온것같아요

제 생각에는 handleMoveFormPage와 handleMoveResultPage 두개를 나눠서 onClick에다가 삼항 연산자로 진행하거나 별도의 변수로 추상화를 진행하는것이 더 좋아보여요!

2023-11-02 22:45 UTC, SEOKKAMONI requested changes

2023-11-02 22:45 UTC, SEOKKAMONI commented on apps/user/src/components/main/ApplicationSubmittionBox/ApplicationPeriodBox/ApplicationPeriodBox.hooks.ts
> +  const submitEnd = 제출_마감_날짜.format('YYYY년 MM월 DD일 (ddd) HH:mm');
```suggestion
  const applicationStart = 제출_시작_날짜.format('YYYY년 MM월 DD일 (ddd) HH:mm');
  const applicationEnd = 제출_마감_날짜.format('YYYY년 MM월 DD일 (ddd) HH:mm');
```

네이밍 공통화를 위해서 다음과 같이 application으로 수정하는거에 대해서 어떻게 생각하시나용

2023-11-02 22:45 UTC, SEOKKAMONI commented on apps/user/src/components/main/ApplicationSubmittionBox/ApplicationPeriodBox/ApplicationPeriodBox.tsx
> +const ApplicationPeriodBoxPeriodBox = () => {
```suggestion

const ApplicationPeriodBox = () => {
```

의도하신건가요..?

2023-11-02 23:26 UTC, arkk200 commented on apps/user/src/components/main/ApplicationSubmittionBox/ApplicationPeriodBox/ApplicationPeriodBox.hooks.ts
> +  const submitEnd = 제출_마감_날짜.format('YYYY년 MM월 DD일 (ddd) HH:mm');
ApplicationPeriodBox 이니 application으로 바꾸는게 일관성 있겠네요👌

2023-11-02 23:48 UTC, SEOKKAMONI commented on apps/user/src/components/main/ApplicationSubmittionBox/ApplicationSubmittionBox.hooks.ts
> +      console.log('결과 확인하기 페이지 이동');
router.push로 결과 확인하기 페이지 이동하게 해주세용

2023-11-04 15:57 UTC, arkk200 commented on apps/user/src/components/main/ApplicationSubmittionBox/ApplicationSubmittionBox.hooks.ts
> +      console.log('결과 확인하기 페이지 이동');
결과 확인하기 페이지 다 안만든 줄 알았습니다👀

2023-11-04 15:58 UTC, arkk200 commented on apps/user/src/components/main/ApplicationSubmittionBox/ApplicationSubmittionBox.hooks.ts
> +      console.log('결과 확인하기 페이지 이동');
넵

2023-11-05 13:01 UTC, SEOKKAMONI commented on apps/user/src/components/main/ApplicationSubmittionBox/ApplicationSubmittionBox.hooks.ts
> +    isSubmitPeriod || isPeriodOfViewing ? 'PRIMARY' : 'DISABLED';
아니면 buttonStyleType은 어떨까여?

2023-11-12 13:57 UTC, arkk200 commented on apps/user/src/components/main/ApplicationSubmittionBox/ApplicationSubmittionBox.hooks.ts
> +      }
헉 else 빼먹었노

2023-11-12 13:57 UTC, arkk200 commented on apps/user/src/components/main/ApplicationSubmittionBox/ApplicationSubmittionBox.hooks.ts
> +    isSubmitPeriod || isPeriodOfViewing ? 'PRIMARY' : 'DISABLED';
스타일 타입이 낫겠네요

2023-11-12 23:19 UTC, SEOKKAMONI approved these changes
LGTM 수고하셨습니당

2023-11-12 23:19 UTC, merged