Feat/#83
Bamdoliro/marururu pull request #84
Opened 2023-06-13 15:13 UTC by SEOKKAMONI

## 📄 Summary
> FAQ 페이지를 만들었습니다

<br>

## 🔨 Tasks
- [ ] FaqLayout
- [ ] Category
- [ ] FaqItem

<br>

## 🙋🏻 More
<img width="1470" alt="image" src="https://github.com/Bamdoliro/marururu/assets/102217654/3706e15c-9f7d-4778-9861-1b32b1156899">

<img width="1466" alt="image" src="https://github.com/Bamdoliro/marururu/assets/102217654/bfacf331-10be-4d51-8b62-619ab013fc16">

리뷰좀 빡세게 부탁드립니다

2023-06-13 23:33 UTC, arkk200 requested changes

2023-06-13 23:33 UTC, arkk200 commented on src/components/faq/Category.tsx
> +const StyledCategory = styled.span<{ isClicked: Boolean }>`
```tsx
const StyledCategory = styled.span<{ isClicked: boolean }>`
```

처럼 불린 타입 원시타입으로 선언해주는게 좋을 것 같습니다.

https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#the-primitives-string-number-and-boolean

2023-06-13 23:33 UTC, arkk200 commented on src/components/faq/CategoryBar.tsx
> +          isClicked={selectedCategory === item.id}
key 프로퍼티 추가해주세요

2023-06-13 23:37 UTC, SEOKKAMONI commented on src/components/faq/CategoryBar.tsx
> +          isClicked={selectedCategory === item.id}
my 스테이크

2023-06-14 00:35 UTC, SEOKKAMONI commented on src/components/faq/Category.tsx
> +const StyledCategory = styled.span<{ isClicked: Boolean }>`
ok!~

2023-06-14 02:33 UTC, arkk200 commented on src/components/faq/CategoryBar.tsx
> +  cursor: pointer;
`cursor: pointer` 속성을 Category 컴포넌트에 적용해줘야할 것 같아요

2023-06-14 02:36 UTC, arkk200 requested changes

2023-06-14 02:36 UTC, arkk200 commented on src/components/faq/FaqItem.tsx
> +  cursor: pointer;
<img width="1440" alt="스크린샷 2023-06-14 오전 11 34 32" src="https://github.com/Bamdoliro/marururu/assets/102217839/1fba8cbb-e52f-43e6-8eeb-a7af6856cfff">

Faq 페이이지에서 Answer 부분에도 커서가 손가락 모양으로 뜨는데 눌러도 반응이 없어요.

`cursur: pointer` 속성을 QuestionBox에만 적용하거나 onClick 이벤트를 StylledFaqItem에 적용해야할 것 같아요.

2023-06-14 03:02 UTC, arkk200 commented
괜찮에요👍

2023-06-14 03:02 UTC, arkk200 approved these changes

2023-06-14 08:34 UTC, merged

2023-06-22 16:25 UTC, ChanhyukPark-Tech commented on src/app/faq/page.tsx
> +  const { data } = useFaqListQuery();
@SEOKKAMONI 

```tsx
 const { data: faqList } = useFaqListQuery();
```

로 한번 rename을 해주는것은 어떠신가요?
20번 Line의 코드만 딱 봤을때는! 
data가 무슨 data지 대체?...라고 생각이 될 것 같아요!

2023-06-22 16:25 UTC, SEOKKAMONI commented on src/app/faq/page.tsx
> +  const { data } = useFaqListQuery();
아 ! 그러네요 네이밍에 대한 고민이있었는데 정말 감사하빈다 !!

2023-06-22 16:27 UTC, SEOKKAMONI commented on src/app/page.tsx
> +import Faq from "@/components/main/FAQ";
헉 사소한 부분을 놓쳤네요 지적해주셔서 감사합니다 !!

2023-06-22 16:28 UTC, ChanhyukPark-Tech commented on src/components/faq/Category.tsx
> +`;
@SEOKKAMONI 
제가 실행시켜보진 않아서 어떤 UI인지 확인은 안되는데요!
onClick이벤트도 받고, cursor pointer까지 주신거면 클릭 가능한 요소라고 생각해요 
클릭가능한 요소라면 button태그를 사용하는것은어때요? 스크린리더기에도 효과적이고, 시멘틱한 태그를 유지하면 Developer Experience도 향상될 것 같아요 
특별히 button태그가 아닌 span 태그를 사용하신 이유가 있으신가요~?

2023-06-22 16:28 UTC, ChanhyukPark-Tech commented on src/components/faq/CategoryBar.tsx
> +  const { data } = useFaqCategoryListQuery();
@SEOKKAMONI 
 마찬가지로 rename이 되면 좋을 것 같아요! 
(사실 이 컴포넌트에서 data는 단 한개라 상관없지만, 추후 이 컴포넌트가 다루는 데이터가 많아질것을 대비한다면요)

2023-06-22 16:29 UTC, ChanhyukPark-Tech commented on src/mocks/handlers/index.ts
> +export const handlers = [...noticeHandlers, ...mainHandlers, ...faqHandlers];
mock까지 관리하시는것 너무 멋집니다!!

2023-06-22 16:48 UTC, ChanhyukPark-Tech commented on src/components/faq/Category.tsx
> +`;
button태그의 기본 스타일을 제거하는게 불편하시다면 
[https://parkjh7764.tistory.com/80](CSS 초기화 리셋 default css)
위와 같이 검색해보세용!

2023-06-25 03:53 UTC, manudeli commented on src/app/faq/page.tsx
> +  const { data } = useFaqListQuery();
@ChanhyukPark-Tech 찬혁님, 객체구조분해할당하지 않고 쓰는 방식은 어떨까요? 저는 이렇게 쓰는데 다른 분들의 생각이 궁금해요

1. 객체의 필드를 사용하는 방식으로 쓰면 변수를 rename하지 않고도 객체를 기준으로 모아서 생각할 수 있다고 생각해요.
2. 새 필드를 사용해야하는 경우나 삭제하는 경우 변경에 유연해요. (아래 코드에 설명)
```tsx
const faqListQuery = useFaqListQuery();

faqListQuery.data
faqListQuery.isLoading // 이와 같이 다른 필드가 추가되야 할때 위에 변수 선언하는 라인의 변경이 없이 필드만 사용하면 됨
faqListQuery.isSuccess // 동일한 설명
```

cc. @SEOKKAMONI