Feat/#90
Bamdoliro/marururu pull request #92
Opened 2023-06-14 22:21 UTC by SEOKKAMONI

## 📄 Summary
> 디자이너의 부탁

<br>

## 🔨 Tasks
- [ ] 스크롤시 SchoolRecuritCard 이미지 fixed
- [ ]  입학 시작 전 D-DAY 띄우기

<br>

## 🙋🏻 More

2023-06-14 23:24 UTC, arkk200 requested changes

2023-06-14 23:24 UTC, arkk200 commented on src/components/main/SchoolRecruitCard.tsx
> +        {moment().isAfter(submitStartTime) ? (
<img width="718" alt="스크린샷 2023-06-15 오전 8 00 06" src="https://github.com/Bamdoliro/marururu/assets/102217839/0e56b8cb-5533-4fe5-bf5c-6812c808ec53">

처럼 원서 모집 종료기간이 지나도 카드가 바뀌지 않는데 조건을 `moment().isAfter(sumbitStartTime) && moment().isBefore(submitEndTime)` 으로 수정해줘야할 것 같습니다.

2023-06-14 23:25 UTC, arkk200 commented
그리고 remainDays 변수에서 원서 접수 시작까지 남은 날짜도 추가해줘야 합니다

2023-06-14 23:49 UTC, arkk200 requested changes

2023-06-14 23:49 UTC, arkk200 commented on src/components/main/SchoolRecruitCard.tsx
> +                {moment().isAfter(submitStartTime) &&
여기 말고 24번째 줄을 수정해야 합니다

2023-06-15 03:09 UTC, arkk200 approved these changes

2023-06-15 03:10 UTC, merged

2023-06-22 16:22 UTC, ChanhyukPark-Tech commented on src/styles/color.ts
>    gray850: "#2B2E36",
색상을 분리해서 관리하는것 너무 좋네요!

2023-06-22 16:23 UTC, SEOKKAMONI commented on src/styles/color.ts
>    gray850: "#2B2E36",
감사합니다 !!!