Feat/#66
Bamdoliro/marururu pull request #95
Opened 2023-06-19 03:08 UTC by SEOKKAMONI

## 📄 Summary
> 원서접수 Progress Bar를 만들었습니다

<br>

## 🔨 Tasks
- [ ] ProgressBar 퍼블리싱
- [ ] useFormPage

<br>

## 🙋🏻 More

<img width="1158" alt="image" src="https://github.com/Bamdoliro/marururu/assets/102217654/6beb4298-cbaf-4805-9442-3460629b020c">

2023-06-19 03:58 UTC, arkk200 commented
<img width="773" alt="스크린샷 2023-06-19 오후 12 56 57" src="https://github.com/Bamdoliro/marururu/assets/102217839/160d072c-4e94-4ee6-a865-a420c3c8265c">

위에 사진처럼 활성화된 단계 이전 단계는 체크 표시로 바꿔주는 것도 추가해줘야 할 것 같습니다.

2023-06-19 04:03 UTC, SEOKKAMONI commented
> 

아이이잉~

2023-06-19 04:20 UTC, arkk200 requested changes

2023-06-19 04:20 UTC, arkk200 commented on src/components/form/ProgressBar.tsx
> +        <Circle
<img width="773" alt="스크린샷 2023-06-19 오후 12 56 57" src="https://github.com/Bamdoliro/marururu/assets/102217839/160d072c-4e94-4ee6-a865-a420c3c8265c">

위에 사진처럼 활성화된 단계 이전 단계는 체크 표시로 바꿔주는 것도 추가해줘야 할 것 같습니다.

2023-06-19 06:26 UTC, arkk200 approved these changes

2023-06-19 06:26 UTC, merged

2023-06-19 06:34 UTC, SEOKKAMONI commented on src/components/form/ProgressBar.tsx
> +        <Circle
폼페이지 개발하면서 개발하려고 TODO에 써놨습니다

2023-06-22 16:13 UTC, ChanhyukPark-Tech commented on src/components/form/ProgressBar.tsx
> +  justify-content: space-between;
스타일링은 개인의 자유이고 취향에 따라서 해도 되지만, 계속해서 반복되는 스타일링은 추상화하여 반복을 줄이면 좋을 것 같아요
이 3줄은 똑같이 80,81,82 라인에도 반복되는데 
[이러한 라이브러리](https://slash.page/libraries/react/emotion-utils/src/flex.i18n/)를 사용하면 한줄로 줄일 수 있을 것 같아요.

2023-06-22 16:13 UTC, ChanhyukPark-Tech commented on src/hooks/useFormPage.ts
> +  );
리액트에서 최적화는 정말로 중요해요.
setter를 한번 실행시키는 엄청 간단한 함수임에도 최적화를 시킬 필요가 있는지 궁금해요!
저는 오히려 최적화를 시키는 로직으로 인해 더욱 성능에 안좋을 것 같아요.
언제 useCallback과 useMemo를 사용해야할지 적절히 판단하는게 중요할 것 같아요 😄

2023-06-22 16:13 UTC, ChanhyukPark-Tech commented on src/components/form/ProgressBar.tsx
> +  justify-content: space-between;
@SEOKKAMONI

2023-06-22 16:13 UTC, ChanhyukPark-Tech commented
@SEOKKAMONI 머지되었지만 리뷰 남겨봤어요 🥳

2023-06-22 16:15 UTC, SEOKKAMONI commented on src/hooks/useFormPage.ts
> +  );
헉 감사합니다 !!!!!!

2023-06-22 16:16 UTC, ChanhyukPark-Tech commented on src/hooks/useFormPage.ts
> +  );
주로 자식 컴포넌트가 memo 로 감싸져있고, 
함수를 Props로 넘길때 reference를 유지하기 위해서 사용하는 편이에요